const express = require('express');
const router = express.Router();
const { v4: uuidv4 } = require('uuid');
const { db } = require('../db/database');
const { PLATFORM_ROLES, ELEVATED_ROLES } = require('../middleware/auth');
// Phase 2.2j: workspace-aware access. Underlying tables (devices, playlists)
// already carry workspace_id from Phase 1; this route can use them even
// though playlists.js itself isn't yet workspace-filtered.
const { resourceAccess } = require('../lib/tenancy');
const { zoneInLayout } = require('../lib/zone-validate');
// #237 + #widget zero-duration loop: one place decides what duration a new item gets —
// explicit value, else the content's own length, else the 10s default (and never a 0).
const { resolveItemDuration } = require('../lib/item-duration');
const { createAutoGeneratedPlaylist } = require('../lib/auto-playlist');
const corpGuard = require('../lib/corporate/guard');

/*
 * ⚠️ CORPORATE: a screen head office's playlist plays on (a mandate) cannot be overridden from
 * here. Its playlist IS the corporate one, so "add to this screen", reorder and copy-to would
 * otherwise either fork around the mandate (a shadowed copy nobody sees) or edit head office's
 * playlist through the back door. Adding content is REDIRECTED into the screen's local slot
 * (redirectAdd below): the store's own content for head office's slot, never head office's playlist.
 */
function mandateRefusal(req, res, deviceId, opts) {
  try { corpGuard.assertNotMandated(req, deviceId, opts); return false; } catch (e) {
    if (corpGuard.send(res, e, req)) return true;
    throw e;
  }
}

// Mark playlist as draft (called after any item mutation)
function markDraft(playlistId) {
  db.prepare("UPDATE playlists SET status = 'draft', updated_at = strftime('%s','now') WHERE id = ?").run(playlistId);
}

// Hardening (#zone-orphan): a zone_id only renders if it belongs to the layout the
// device is actually showing. Assigning a zone from a DIFFERENT layout (e.g. after a
// layout switch/duplicate) creates an item that the players can't place. We CLEAR a
// stale zone_id to null here (-> "unassigned", which the players route sensibly) rather
// than reject, so this can't break a caller; the cleared write is logged. NOTE for
// review: switch to a 400 reject if you'd rather surface the bad zone to the operator.
// Returns the zone_id to persist (the given one, or null if it isn't in the device's
// active layout). deviceLayoutId may be null (device on fullscreen) -> any zone_id is
// stale, so cleared.
function validZoneForLayout(zoneId, deviceLayoutId, ctx) {
  if (!zoneId) return null;
  if (zoneInLayout(zoneId, deviceLayoutId)) return zoneId;
  console.warn(`[assign] cleared stale zone_id ${zoneId} (not in active layout ${deviceLayoutId || 'none'})${ctx ? ' ' + ctx : ''}`);
  return null;
}

// Phase 2.2j: workspace-aware device access check. Returns access context
// (with workspaceRole/actingAs) or null. Caller decides if read or write.
/*
 * explicitId is for the item-scoped routes, where the device is named in the BODY or QUERY rather
 * than the path — device_id there decides whose screen a fork belongs to, so it must be authorised
 * exactly like a path param. Passing it through req.params was the obvious shortcut and would have
 * silently skipped this check, because req.params has no such key.
 */
function checkDeviceAccess(req, res, paramName = 'deviceId', requireWrite = true, explicitId = null) {
  const deviceId = explicitId || req.params[paramName];
  const device = db.prepare('SELECT workspace_id FROM devices WHERE id = ?').get(deviceId);
  if (!device) { res.status(404).json({ error: 'Device not found' }); return null; }
  if (!device.workspace_id) { res.status(403).json({ error: 'Device not assigned to a workspace' }); return null; }
  const ws = db.prepare('SELECT * FROM workspaces WHERE id = ?').get(device.workspace_id);
  const ctx = ws && resourceAccess(req, ws);
  if (!ctx) { res.status(403).json({ error: 'Access denied' }); return null; }
  if (requireWrite && !ctx.actingAs && ctx.workspaceRole === 'workspace_viewer') {
    res.status(403).json({ error: 'Read-only access' }); return null;
  }
  return { device, ctx };
}

// Ensure device has a playlist; auto-create one if missing.
// Phase 2.2j: stamps workspace_id on the auto-created playlist so it remains
// visible once playlists.js migrates. Mirrors the 2.2i fix in device-groups.js.
function ensureDevicePlaylist(deviceId, userId) {
  const device = db.prepare('SELECT playlist_id, workspace_id, name FROM devices WHERE id = ?').get(deviceId);
  /*
   * ⚠️ A per-device edit on an INHERITING screen forks, rather than editing the shared playlist.
   *
   * "Add content to this screen" used to edit the group's playlist and therefore every other screen
   * in the group. That was never intended — it fell out of every device holding a copy of the same
   * playlist id — and the device page now labels such a screen "Inherited from Lobby" right beside
   * the Add Content button, which makes the old behaviour read as a bug rather than a design.
   *
   * forkInheritedPlaylist copies the inherited playlist (items, nesting, mute, per-item schedules
   * AND its published snapshot, so the screen does not go dark before the operator publishes) into
   * one owned by this device, and stamps playlist_source = 'device'.
   */
  const forked = forkInheritedPlaylist(deviceId, userId);
  if (forked) return forked.playlistId;

  // Already this screen's own, or driven by an active schedule: edit it in place.
  const resolved = resolveDevicePlaylistId(deviceId);
  if (resolved) return resolved;

  const playlistId = createAutoGeneratedPlaylist(db, {
    name: `${device?.name || 'Display'} playlist`,
    workspaceId: device?.workspace_id || null, userId,
  });
  // A playlist made FOR this screen is a choice, not an inheritance: stamp it, or the resolver
  // would look straight past it at the group and the new playlist would never play.
  db.prepare("UPDATE devices SET playlist_id = ?, playlist_source = 'device' WHERE id = ?").run(playlistId, deviceId);
  return playlistId;
}

// Standard item query with joined content/widget info
const ITEM_SELECT = `
  SELECT pi.id, pi.playlist_id, pi.content_id, pi.widget_id, pi.child_playlist_id, pi.zone_id, pi.sort_order, pi.duration_sec, pi.muted,
         pi.created_at, pi.updated_at,
         COALESCE(c.filename, w.name, cp.name) as filename,
         cp.name as child_playlist_name,
         c.mime_type, c.filepath, c.thumbnail_path,
         c.duration_sec as content_duration, c.file_size, c.remote_url,
         w.name as widget_name, w.widget_type, w.config as widget_config
  FROM playlist_items pi
  LEFT JOIN content c ON pi.content_id = c.id
  LEFT JOIN widgets w ON pi.widget_id = w.id
  LEFT JOIN playlists cp ON pi.child_playlist_id = cp.id
`;

// Get assignments (playlist items) for a device
router.get('/device/:deviceId', (req, res) => {
  if (!checkDeviceAccess(req, res, 'deviceId', false)) return;
  const device = db.prepare('SELECT playlist_id FROM devices WHERE id = ?').get(req.params.deviceId);
  if (!device?.playlist_id) return res.json([]);

  const items = db.prepare(`${ITEM_SELECT} WHERE pi.playlist_id = ? ORDER BY pi.sort_order ASC`)
    .all(device.playlist_id);
  res.json(items);
});

// Add content or widget to device playlist.
// Phase 2.2j: closes 2 pre-existing cross-tenant leaks:
//   1. Content gate: today checks content.user_id == caller. A workspace_admin
//      who happens to own content in another workspace could push it into a
//      device in this workspace. Now: content must be in device's workspace
//      (or be a platform-template, workspace_id IS NULL).
//   2. Widget gate: today checks ONLY existence - any user could attach any
//      widget UUID to their own device's playlist. Now: widget must be in
//      device's workspace (or be a platform-template).
router.post('/device/:deviceId', (req, res) => {
  const access = checkDeviceAccess(req, res, 'deviceId', true);
  if (!access) return;
  {
    const mandate = corpGuard.activeMandateFor(db, req.params.deviceId);
    if (mandate) return redirectAdd(req, res, access, mandate);
  }
  const { content_id, widget_id, child_playlist_id, zone_id, sort_order } = req.body;

  if (!content_id && !widget_id && !child_playlist_id) return res.status(400).json({ error: 'content_id, widget_id or child_playlist_id required' });
  if ([content_id, widget_id, child_playlist_id].filter(Boolean).length > 1) {
    return res.status(400).json({ error: 'an item is content, a widget, or a child playlist — not more than one' });
  }

  let content = null;
  if (content_id) {
    content = db.prepare('SELECT id, workspace_id, duration_sec FROM content WHERE id = ?').get(content_id);
    if (!content) return res.status(404).json({ error: 'Content not found' });
    if (content.workspace_id && content.workspace_id !== access.device.workspace_id) {
      return res.status(403).json({ error: 'Content is not in this device\'s workspace' });
    }
  }
  // #237: pushing a video straight at a display is the shortest path in the product, so it
  // has to default to the clip's length too — not the 10s that cut it off mid-play.
  const duration_sec = resolveItemDuration(req.body.duration_sec, content);
  if (widget_id) {
    const widget = db.prepare('SELECT id, workspace_id FROM widgets WHERE id = ?').get(widget_id);
    if (!widget) return res.status(404).json({ error: 'Widget not found' });
    if (widget.workspace_id && widget.workspace_id !== access.device.workspace_id) {
      return res.status(403).json({ error: 'Widget is not in this device\'s workspace' });
    }
  }

  // A playlist nested into the display's own playlist: the same rules as Playlists → + Add
  // Content (lib/playlist-nesting.js), checked against the display's workspace BEFORE its playlist
  // is created, so a refused nesting does not leave an empty playlist behind.
  if (child_playlist_id) {
    const existing = db.prepare('SELECT playlist_id FROM devices WHERE id = ?').get(req.params.deviceId);
    const bad = require('../lib/playlist-nesting').nestingError(db, existing && existing.playlist_id, child_playlist_id, access.device.workspace_id);
    if (bad) return res.status(bad.status).json({ error: bad.error });
  }

  const playlistId = ensureDevicePlaylist(req.params.deviceId, req.user.id);
  { const smartErr = require('../lib/smart-playlist').smartAddError(db, playlistId); if (smartErr) return res.status(400).json({ error: smartErr }); }
  if (child_playlist_id) {
    const bad = require('../lib/playlist-nesting').nestingError(db, playlistId, child_playlist_id, access.device.workspace_id);
    if (bad) return res.status(bad.status).json({ error: bad.error });
  }

  // Hardening: clear a zone_id that isn't in THIS device's active layout (prevents new orphans).
  const devLayout = db.prepare('SELECT layout_id FROM devices WHERE id = ?').get(req.params.deviceId);
  const effZone = validZoneForLayout(zone_id, devLayout?.layout_id, `on add to device ${req.params.deviceId}`);

  let order = sort_order;
  if (order === undefined || order === null) {
    const max = db.prepare('SELECT MAX(sort_order) as max_order FROM playlist_items WHERE playlist_id = ?')
      .get(playlistId);
    order = (max.max_order || 0) + 1;
  }

  try {
    const result = db.prepare(`
      INSERT INTO playlist_items (playlist_id, content_id, widget_id, child_playlist_id, zone_id, sort_order, duration_sec)
      VALUES (?, ?, ?, ?, ?, ?, ?)
    `).run(playlistId, content_id || null, widget_id || null, child_playlist_id || null, effZone, order, duration_sec);

    markDraft(playlistId);

    const item = db.prepare(`${ITEM_SELECT} WHERE pi.id = ?`).get(result.lastInsertRowid);
    res.status(201).json(item);
  } catch (err) {
    if (err.message.includes('UNIQUE')) {
      return res.status(409).json({ error: 'Content already in playlist' });
    }
    throw err;
  }
});

/*
 * "Add content to this screen" on a screen head office's playlist plays on (spec §4.3, critique U1).
 * The item goes into the screen's LOCAL SLOT content, never into head office's playlist:
 *   - no slot -> CORPORATE_NO_SLOT; several and no slot_id -> 409 CORPORATE_SLOT_REQUIRED {slots};
 *   - fill_scope 'nearest' (default): the content this screen already plays for the slot, at
 *     whatever level it lives (screen, video wall, group, everyone in the workspace); none yet ->
 *     the workspace-level content, created;
 *   - fill_scope 'device': this screen only (its video wall, for a wall member), made as a copy of
 *     the nearest so nothing disappears.
 * Never a silent fork: the 201 says exactly where it went and how many screens that reaches
 * (`redirected_to`). Like any edit it lands in the draft; publishing it is what puts it on screen.
 */
function redirectAdd(req, res, access, mandate) {
  const fillsLib = require('../lib/corporate/fills');
  const { content_id, widget_id, child_playlist_id } = req.body || {};
  if (!content_id && !widget_id && !child_playlist_id) return res.status(400).json({ error: 'content_id, widget_id or child_playlist_id required' });
  if ([content_id, widget_id, child_playlist_id].filter(Boolean).length > 1) {
    return res.status(400).json({ error: 'an item is content, a widget, or a child playlist — not more than one' });
  }
  try {
    if (child_playlist_id) throw corpGuard.err('FILL_FLAT');
    let content = null;
    if (content_id) {
      content = db.prepare('SELECT id, workspace_id, duration_sec, mime_type FROM content WHERE id = ?').get(content_id);
      if (!content) return res.status(404).json({ error: 'Content not found' });
      if (content.workspace_id && content.workspace_id !== access.device.workspace_id) {
        return res.status(403).json({ error: 'Content is not in this device\'s workspace' });
      }
    }
    if (widget_id) {
      const widget = db.prepare('SELECT id, workspace_id FROM widgets WHERE id = ?').get(widget_id);
      if (!widget) return res.status(404).json({ error: 'Widget not found' });
      if (widget.workspace_id && widget.workspace_id !== access.device.workspace_id) {
        return res.status(403).json({ error: 'Widget is not in this device\'s workspace' });
      }
    }
    const duration_sec = resolveItemDuration(req.body.duration_sec, content);
    const item = { content_id: content_id || null, widget_id: widget_id || null, duration_sec };
    const scope = req.body.fill_scope === 'device' ? 'device' : 'nearest';
    let target = null;
    let itemId = null;
    db.transaction(() => {
      target = fillsLib.redirectTarget(db, mandate, req.params.deviceId, { slotId: req.body.slot_id || null, scope, userId: req.user.id });
      fillsLib.assertCanAdd(db, target.fill.fill_playlist_id, [item]);
      const max = db.prepare('SELECT MAX(sort_order) AS m FROM playlist_items WHERE playlist_id = ?').get(target.fill.fill_playlist_id);
      itemId = db.prepare('INSERT INTO playlist_items (playlist_id, content_id, widget_id, sort_order, duration_sec) VALUES (?, ?, ?, ?, ?)')
        .run(target.fill.fill_playlist_id, item.content_id, item.widget_id, ((max && max.m) || 0) + 1, duration_sec).lastInsertRowid;
      markDraft(target.fill.fill_playlist_id);
    })();
    const out = db.prepare(`${ITEM_SELECT} WHERE pi.id = ?`).get(itemId);
    res.status(201).json({ ...out, redirected_to: { ...fillsLib.describeFill(db, target.fill, target.slot), created: !!target.created } });
  } catch (e) {
    if (corpGuard.send(res, e, req)) return undefined;
    throw e;
  }
  return undefined;
}

// Helper: load a playlist item and check write access via the parent
// playlist's workspace. Returns the item row or null after sending 403/404.
function checkItemWrite(req, res) {
  const item = db.prepare('SELECT pi.*, p.workspace_id AS pl_workspace_id FROM playlist_items pi JOIN playlists p ON pi.playlist_id = p.id WHERE pi.id = ?').get(req.params.id);
  if (!item) { res.status(404).json({ error: 'Item not found' }); return null; }
  if (!item.pl_workspace_id) { res.status(403).json({ error: 'Playlist not assigned to a workspace' }); return null; }
  const ws = db.prepare('SELECT * FROM workspaces WHERE id = ?').get(item.pl_workspace_id);
  const ctx = ws && resourceAccess(req, ws);
  if (!ctx) { res.status(403).json({ error: 'Access denied' }); return null; }
  if (!ctx.actingAs && ctx.workspaceRole === 'workspace_viewer') {
    res.status(403).json({ error: 'Read-only access' }); return null;
  }
  /*
   * CORPORATE: an item of head office's playlist (or of a child of it). Edited "on a screen" (the
   * device page passes device_id) it is refused for everyone — a store user is told it is locked,
   * an author is pointed at the corporate editor. Without device_id (the API) authors may edit it
   * in place, as in the playlist editor; anyone else is refused by assertPlaylistWritable.
   */
  try {
    const g = corpGuard.governanceOf(db, item.playlist_id);
    if ((g.kind === 'corporate' || g.kind === 'corporate_child') && (req.body?.device_id || req.query?.device_id)) {
      const vars = { name: g.corporatePlaylist.name };
      const details = { corporate: { playlist_id: g.corporatePlaylist.id, playlist_name: g.corporatePlaylist.name } };
      throw corpGuard.canAuthor(req, g.orgId) && !req.viaToken
        ? corpGuard.err('CORPORATE_EDIT_IN_EDITOR', vars, details)
        : corpGuard.err('CORPORATE_LOCKED', vars, details);
    }
    corpGuard.assertPlaylistWritable(req, { id: item.playlist_id }, 'items');
  } catch (e) {
    if (corpGuard.send(res, e, req)) return null;
    throw e;
  }
  return item;
}

/*
 * An item of a store's slot content, edited "on a screen" (spec §4.3): the edit lands on the content
 * the item lives in (every screen that plays it — the response says which level and how many), or,
 * with fill_scope 'device', on this screen's own copy (made from it, item ids mapped).
 * @returns null (not slot content), false (a response was sent), or {itemId, describe}
 */
function fillItemTarget(req, res, item, deviceId, fillScope) {
  const fillsLib = require('../lib/corporate/fills');
  const rows = fillsLib.fillsOfPlaylist(db, item.playlist_id);
  if (!rows.length) return null;
  const fill = rows[0];
  const slot = fillsLib.slotRow(db, fill.slot_id);
  if (fillScope !== 'device' || !slot) return { itemId: item.id, describe: fillsLib.describeFill(db, fill, slot) };
  try {
    const own = db.transaction(() => fillsLib.ensureFillForDevice(db, deviceId, slot, { scope: 'device', userId: req.user.id }))();
    if (!own) return { itemId: item.id, describe: fillsLib.describeFill(db, fill, slot) };
    let mapped = item.id;
    if (own.fill.fill_playlist_id !== item.playlist_id) {
      // The copy was made from the nearest content; map by id when it was this one, else by position.
      mapped = own.itemIdMap.get(Number(item.id)) ?? own.itemIdMap.get(item.id) ?? null;
      if (mapped === null) {
        const srcIdx = db.prepare('SELECT COUNT(*) AS n FROM playlist_items WHERE playlist_id = ? AND (sort_order < ? OR (sort_order = ? AND id < ?))')
          .get(item.playlist_id, item.sort_order, item.sort_order, item.id).n;
        const row = db.prepare('SELECT id FROM playlist_items WHERE playlist_id = ? ORDER BY sort_order ASC, id ASC LIMIT 1 OFFSET ?').get(own.fill.fill_playlist_id, srcIdx);
        if (!row) { res.status(409).json({ error: 'This screen\'s own slot content no longer has that item.' }); return false; }
        mapped = row.id;
      }
    }
    return { itemId: mapped, describe: fillsLib.describeFill(db, own.fill, slot) };
  } catch (e) {
    if (corpGuard.send(res, e, req)) return false;
    throw e;
  }
}

// Per-item mute lives in lib/mute-sync.js so routes/playlists.js can share it.
const { emitMuteChanged } = require('../lib/mute-sync');
const { resolveDevicePlaylistId } = require('../lib/resolve-device-playlist');
const { forkInheritedPlaylist, forkForItemEdit } = require('../lib/fork-device-playlist');

// Update playlist item
router.put('/:id', (req, res) => {
  let item = checkItemWrite(req, res);
  if (!item) return;

  /*
   * ⚠️ device_id turns an item-scoped edit back into a per-screen one.
   *
   * This endpoint is addressed by ITEM, so it cannot know whose screen is being edited — a shared
   * playlist has many. Editing an item on a screen that INHERITS therefore changed that item for
   * every screen in the group. The device page passes device_id so the same fork-on-write rule as
   * "add content to this screen" applies here; without it (the group page, the API) the item is
   * edited where it lives, which is correct for those callers.
   */
  let editedFill = null;
  if (req.body.device_id) {
    if (!checkDeviceAccess(req, res, 'body_device_id', true, req.body.device_id)) return;
    // Store slot content edited on a screen: in place (default), or for this screen only.
    const f = fillItemTarget(req, res, item, req.body.device_id, req.body.fill_scope);
    if (f === false) return;
    if (f) { editedFill = f.describe; if (f.itemId !== item.id) { req.params.id = f.itemId; item = db.prepare('SELECT * FROM playlist_items WHERE id = ?').get(f.itemId); } }
    const forkedItemId = f ? item.id : forkForItemEdit(req.body.device_id, req.user.id, req.params.id);
    if (String(forkedItemId) !== String(req.params.id)) {
      req.params.id = forkedItemId;
      item = db.prepare('SELECT * FROM playlist_items WHERE id = ?').get(forkedItemId);
    }
  }

  const { sort_order, duration_sec, zone_id, muted } = req.body;
  const updates = [];
  const values = [];

  if (sort_order !== undefined) { updates.push('sort_order = ?'); values.push(sort_order); }
  if (duration_sec !== undefined) { updates.push('duration_sec = ?'); values.push(resolveItemDuration(duration_sec, null)); }
  // zone_id can be null (clear the zone) - treat undefined as "no change",
  // any other value (including null) as "write this".
  if (zone_id !== undefined) {
    // Hardening: if this playlist is bound to exactly ONE device with a layout, clear a
    // zone_id that isn't in that layout (prevents new orphans). Multi-device / fullscreen
    // playlists can't be bound to one layout here, so we leave those to the player fallback.
    let effZone = zone_id || null;
    if (effZone) {
      const devs = db.prepare(`SELECT d.layout_id FROM devices d
        JOIN device_resolved_playlist r ON r.device_id = d.id
        WHERE r.playlist_id = ? AND d.layout_id IS NOT NULL AND d.wall_id IS NULL`).all(item.playlist_id);
      if (devs.length === 1) effZone = validZoneForLayout(effZone, devs[0].layout_id, `on update of item ${req.params.id}`);
      // A wall's playlist is placed by the WALL's layout (lib/wall-layout.js), not a member's.
      else if (devs.length === 0) {
        const walls = db.prepare('SELECT layout_id FROM video_walls WHERE playlist_id = ? AND layout_id IS NOT NULL').all(item.playlist_id);
        if (walls.length === 1) effZone = validZoneForLayout(effZone, walls[0].layout_id, `on update of wall item ${req.params.id}`);
      }
    }
    updates.push('zone_id = ?'); values.push(effZone);
  }
  // #129: per-item mute (coerced to 0/1). Was silently dropped here before, so the
  // dashboard toggle did nothing.
  const mutedChanged = muted !== undefined && (item.muted ? 1 : 0) !== (muted ? 1 : 0);
  if (muted !== undefined) { updates.push('muted = ?'); values.push(muted ? 1 : 0); }

  if (updates.length > 0) {
    updates.push("updated_at = strftime('%s','now')");
    values.push(req.params.id);
    db.prepare(`UPDATE playlist_items SET ${updates.join(', ')} WHERE id = ?`).run(...values);
    markDraft(item.playlist_id);
    if (mutedChanged) emitMuteChanged(req, item, muted ? 1 : 0);
  }

  const updated = db.prepare(`${ITEM_SELECT} WHERE pi.id = ?`).get(req.params.id);
  res.json(editedFill ? { ...updated, edited_fill: editedFill } : updated);
});

// Delete playlist item
router.delete('/:id', (req, res) => {
  let item = checkItemWrite(req, res);
  if (!item) return;

  // Same rule as PUT above: removing an item from a screen that inherits used to remove it from
  // every screen in the group. device_id (query param here — a DELETE carries no body from the
  // dashboard) says which screen is meant.
  const deviceId = req.query.device_id;
  let editedFill = null;
  if (deviceId) {
    if (!checkDeviceAccess(req, res, 'query_device_id', true, deviceId)) return;
    const f = fillItemTarget(req, res, item, deviceId, req.query.fill_scope);
    if (f === false) return;
    if (f) { editedFill = f.describe; if (f.itemId !== item.id) { req.params.id = f.itemId; item = db.prepare('SELECT * FROM playlist_items WHERE id = ?').get(f.itemId); } }
    const forkedItemId = f ? item.id : forkForItemEdit(deviceId, req.user.id, req.params.id);
    if (String(forkedItemId) !== String(req.params.id)) {
      req.params.id = forkedItemId;
      item = db.prepare('SELECT * FROM playlist_items WHERE id = ?').get(forkedItemId);
    }
  }

  db.prepare('DELETE FROM playlist_items WHERE id = ?').run(req.params.id);
  markDraft(item.playlist_id);

  res.json({ success: true, content_id: item.content_id, ...(editedFill ? { edited_fill: editedFill } : {}) });
});

// Reorder items for a device's playlist
router.post('/device/:deviceId/reorder', (req, res) => {
  if (!checkDeviceAccess(req, res, 'deviceId', true)) return;
  // Corporate items keep their order (Stage B: a store reorders its own items inside its slot).
  if (mandateRefusal(req, res, req.params.deviceId, { storeCode: 'CORPORATE_LOCKED' })) return;
  const { order } = req.body;
  if (!Array.isArray(order)) return res.status(400).json({ error: 'order must be an array of item IDs' });

  /*
   * ⚠️ Resolved, and forked. This read devices.playlist_id directly, which is NULL for a screen
   * that inherits now that the copies are gone — so a drag-and-drop on an inheriting screen
   * silently returned an empty list and reordered nothing.
   *
   * Reordering "this screen" is a per-device edit like any other, so it forks; the ids the client
   * sent belong to the shared playlist and are translated to the fork's equivalents. Without the
   * translation the UPDATE would match nothing (they are in a different playlist) and the reorder
   * would appear to succeed while changing nothing at all.
   */
  const forked = forkInheritedPlaylist(req.params.deviceId, req.user.id);
  const playlistId = forked ? forked.playlistId : resolveDevicePlaylistId(req.params.deviceId);
  if (!playlistId) return res.json([]);
  const mapId = (itemId) => (forked ? (forked.itemIdMap.get(Number(itemId)) ?? itemId) : itemId);

  const updateStmt = db.prepare('UPDATE playlist_items SET sort_order = ? WHERE id = ? AND playlist_id = ?');
  const transaction = db.transaction(() => {
    order.forEach((itemId, index) => {
      updateStmt.run(index, mapId(itemId), playlistId);
    });
  });
  transaction();

  markDraft(playlistId);

  const items = db.prepare(`${ITEM_SELECT} WHERE pi.playlist_id = ? ORDER BY pi.sort_order ASC`)
    .all(playlistId);
  res.json(items);
});

// Copy playlist from one device to another.
// Phase 2.2j: closes a pre-existing cross-tenant leak. Today both deviceIds
// only got the user_id ownership check; a caller with reach into a foreign
// workspace could copy that workspace's playlist into a device in their own
// workspace (or vice versa). Now: both devices must be in the same workspace,
// and the caller must have write access there.
router.post('/device/:deviceId/copy-to/:targetDeviceId', (req, res) => {
  const sourceAccess = checkDeviceAccess(req, res, 'deviceId', true);
  if (!sourceAccess) return;
  const targetAccess = checkDeviceAccess(req, res, 'targetDeviceId', true);
  if (!targetAccess) return;
  if (sourceAccess.device.workspace_id !== targetAccess.device.workspace_id) {
    return res.status(403).json({ error: 'Source and target devices must be in the same workspace' });
  }
  // A mandated target plays head office's playlist; a copy onto it would never show.
  if (mandateRefusal(req, res, req.params.targetDeviceId)) return;

  const sourceDevice = db.prepare('SELECT playlist_id FROM devices WHERE id = ?').get(req.params.deviceId);
  if (!sourceDevice?.playlist_id) return res.status(404).json({ error: 'Source device has no playlist' });

  const allSource = db.prepare('SELECT * FROM playlist_items WHERE playlist_id = ? ORDER BY sort_order')
    .all(sourceDevice.playlist_id);
  // A local slot row only means something inside its corporate playlist; copied it would be a ghost
  // item (spec §6.1-4). Skipped and counted.
  const sourceItems = allSource.filter((a) => !a.slot_id);
  const skippedSlots = allSource.length - sourceItems.length;
  if (!sourceItems.length) return res.status(404).json({ error: 'Source playlist is empty' });

  const target = db.prepare('SELECT id, user_id FROM devices WHERE id = ?').get(req.params.targetDeviceId);
  if (!target) return res.status(404).json({ error: 'Target device not found' });

  const targetPlaylistId = ensureDevicePlaylist(req.params.targetDeviceId, target.user_id || req.user.id);
  { const smartErr = require('../lib/smart-playlist').smartAddError(db, targetPlaylistId); if (smartErr) return res.status(400).json({ error: smartErr }); }

  if (req.body.replace) {
    db.prepare('DELETE FROM playlist_items WHERE playlist_id = ?').run(targetPlaylistId);
  }

  const maxOrder = db.prepare('SELECT MAX(sort_order) as m FROM playlist_items WHERE playlist_id = ?')
    .get(targetPlaylistId).m || 0;
  /*
   * ⚠️ Nested items copy as REFERENCES, not as a flattened copy of the child's contents — the
   * whole point of nesting is that editing the child reaches every parent, and flattening here
   * would quietly sever that for the target device.
   *
   * But depth still has to hold. If the target's own playlist is already used inside another
   * playlist, dropping a child into it builds a two-level chain from the far end — the same hole
   * the reverse guard in routes/playlists.js closes at add time. Refuse, and name the playlist, so
   * the operator can see why rather than discovering a silently short playlist later.
   */
  if (sourceItems.some((a) => a.child_playlist_id)) {
    const parent = db.prepare(`
      SELECT p.name FROM playlist_items pi
        JOIN playlists p ON p.id = pi.playlist_id
       WHERE pi.child_playlist_id = ? LIMIT 1
    `).get(targetPlaylistId);
    if (parent) {
      return res.status(400).json({
        error: `The source contains a nested playlist, and the target device's playlist is already `
          + `used inside "${parent.name}" — playlists may only nest one level deep.`,
      });
    }
  }

  const stmt = db.prepare('INSERT INTO playlist_items (playlist_id, content_id, widget_id, child_playlist_id, zone_id, sort_order, duration_sec) VALUES (?, ?, ?, ?, ?, ?, ?)');

  const transaction = db.transaction(() => {
    sourceItems.forEach((a, i) => {
      stmt.run(targetPlaylistId, a.content_id, a.widget_id, a.child_playlist_id || null, a.zone_id || null, maxOrder + i + 1, resolveItemDuration(a.duration_sec, null));
    });
  });
  transaction();

  markDraft(targetPlaylistId);
  res.json({ success: true, copied: sourceItems.length, ...(skippedSlots ? { skipped_slots: skippedSlots } : {}) });
});

module.exports = router;
