'use strict';

// server/lib/auto-playlist.js owns the is_auto_generated flag by construction. These tests
// pin the three behaviours the Playlists toggle depends on, without booting the server:
//
//   - backfillScheduledPlaylists derives the flag from the schedules table, never from the
//     `Scheduled:` display name (user-editable in both directions);
//   - schedule DELETE / PUT collect a throwaway only while it is still an untouched
//     throwaway (auto-generated, single item, unreferenced);
//   - PUT content changes rewrite that single item.

const { test } = require('node:test');
const assert = require('node:assert/strict');
// The runtime driver shim, not better-sqlite3 directly: the native binding is not built on
// every machine (player images, fresh checkouts), and the shim is exactly what the app boots.
const { Database } = require('../db/sqlite-driver');
const {
  createAutoGeneratedPlaylist,
  backfillScheduledPlaylists,
  deleteAutoGeneratedPlaylistIfOrphan,
  rewriteScheduledPlaylistItem,
} = require('../lib/auto-playlist');

function memdb() {
  const db = new Database(':memory:');
  db.exec(`
    CREATE TABLE playlists (id TEXT PRIMARY KEY, user_id TEXT, workspace_id TEXT, name TEXT NOT NULL,
      description TEXT DEFAULT '', status TEXT NOT NULL DEFAULT 'draft', is_auto_generated INTEGER NOT NULL DEFAULT 0,
      published_snapshot TEXT, published_structure TEXT,
      created_at INTEGER DEFAULT 0, updated_at INTEGER DEFAULT 0);
    CREATE TABLE schedules (id TEXT PRIMARY KEY, content_id TEXT, playlist_id TEXT);
    CREATE TABLE playlist_items (id INTEGER PRIMARY KEY AUTOINCREMENT, playlist_id TEXT,
      content_id TEXT, sort_order INTEGER DEFAULT 0, duration_sec INTEGER DEFAULT 10);
    CREATE TABLE content (id TEXT PRIMARY KEY, filename TEXT, duration_sec REAL);
    CREATE TABLE devices (id TEXT PRIMARY KEY, playlist_id TEXT, scheduled_playlist_id TEXT);
    CREATE TABLE device_groups (id TEXT PRIMARY KEY, playlist_id TEXT);
    CREATE TABLE video_walls (id TEXT PRIMARY KEY, playlist_id TEXT);
    CREATE TABLE slide_decks (id TEXT PRIMARY KEY, playlist_id TEXT);
    CREATE TABLE api_token_targets (token_id TEXT NOT NULL, playlist_id TEXT NOT NULL,
      created_at INTEGER DEFAULT 0, PRIMARY KEY (token_id, playlist_id));
    CREATE TABLE agency_notifications (id INTEGER PRIMARY KEY AUTOINCREMENT, playlist_id TEXT NOT NULL);
  `);
  return db;
}

function seedScheduleThrowaway(db, { schedId = 's1', contentId = 'c1', playlistName = 'Scheduled: promo.jpg', flagged = 0 } = {}) {
  db.prepare("INSERT INTO content (id, filename, duration_sec) VALUES (?, 'promo.jpg', 25)").run(contentId);
  db.prepare('INSERT INTO playlists (id, user_id, name, is_auto_generated) VALUES (?,?,?,?)')
    .run('pl1', 'u', playlistName, flagged);
  db.prepare('INSERT INTO playlist_items (playlist_id, content_id, sort_order, duration_sec) VALUES (?,?,0,25)')
    .run('pl1', contentId);
  db.prepare('INSERT INTO schedules (id, content_id, playlist_id) VALUES (?,?,?)').run(schedId, contentId, 'pl1');
  return 'pl1';
}

test('createAutoGeneratedPlaylist stamps the flag and mirrors table defaults', () => {
  const db = memdb();
  const id = createAutoGeneratedPlaylist(db, { name: 'Lobby playlist', workspaceId: 'ws', userId: 'u' });
  const row = db.prepare('SELECT * FROM playlists WHERE id = ?').get(id);
  assert.equal(row.is_auto_generated, 1);
  assert.equal(row.status, 'draft');
  assert.equal(row.description, '');
  assert.equal(row.workspace_id, 'ws');
});

test('backfill flags the schedule target even when renamed', () => {
  const db = memdb();
  seedScheduleThrowaway(db, { playlistName: 'Morning lobby loop' });
  assert.equal(backfillScheduledPlaylists(db), 1);
  assert.equal(db.prepare('SELECT is_auto_generated FROM playlists WHERE id = ?').get('pl1').is_auto_generated, 1);
});

test('backfill ignores a hand-made playlist that shares the prefix', () => {
  const db = memdb();
  db.prepare("INSERT INTO playlists (id, user_id, name, is_auto_generated) VALUES ('ph','u','Scheduled: my picks',0)").run();
  assert.equal(backfillScheduledPlaylists(db), 0);
  assert.equal(db.prepare('SELECT is_auto_generated FROM playlists WHERE id = ?').get('ph').is_auto_generated, 0);
});

test('backfill ignores playlists no content-schedule points at', () => {
  const db = memdb();
  db.prepare("INSERT INTO playlists (id, user_id, name) VALUES ('p','u','Mine')").run();
  db.prepare("INSERT INTO content (id, filename) VALUES ('c','x.jpg')").run();
  db.prepare("INSERT INTO schedules (id, content_id, playlist_id) VALUES ('s','c',NULL)").run();
  db.prepare("INSERT INTO schedules (id, content_id, playlist_id) VALUES ('s2',NULL,'p')").run();
  assert.equal(backfillScheduledPlaylists(db), 0);
});

test('deleteAutoGeneratedPlaylistIfOrphan removes an untouched throwaway', () => {
  const db = memdb();
  seedScheduleThrowaway(db, { flagged: 1 });
  db.prepare('DELETE FROM schedules WHERE id = ?').run('s1');
  assert.equal(deleteAutoGeneratedPlaylistIfOrphan(db, 'pl1'), true);
  assert.equal(db.prepare('SELECT id FROM playlists WHERE id = ?').get('pl1'), undefined);
  assert.equal(db.prepare('SELECT COUNT(*) n FROM playlist_items WHERE playlist_id = ?').get('pl1').n, 0);
});

test('deleteAutoGeneratedPlaylistIfOrphan keeps adopted, shared and plain rows', () => {
  const db = memdb();
  seedScheduleThrowaway(db, { flagged: 1 });
  db.prepare('DELETE FROM schedules WHERE id = ?').run('s1');

  // Adopted: a human added a second item.
  db.prepare("INSERT INTO playlist_items (playlist_id, content_id, sort_order) VALUES ('pl1','c1',1)").run();
  assert.equal(deleteAutoGeneratedPlaylistIfOrphan(db, 'pl1'), false);

  // Shared: a device points at it.
  db.prepare('DELETE FROM playlist_items WHERE playlist_id = ? AND sort_order = 1').run('pl1');
  db.prepare("INSERT INTO devices (id, playlist_id) VALUES ('d','pl1')").run();
  assert.equal(deleteAutoGeneratedPlaylistIfOrphan(db, 'pl1'), false);

  // Plain: never generated.
  db.prepare('UPDATE playlists SET is_auto_generated = 0 WHERE id = ?').run('pl1');
  db.prepare('DELETE FROM devices WHERE id = ?').run('d');
  assert.equal(deleteAutoGeneratedPlaylistIfOrphan(db, 'pl1'), false);

  // Missing: nothing to do.
  assert.equal(deleteAutoGeneratedPlaylistIfOrphan(db, 'nope'), false);
  assert.equal(deleteAutoGeneratedPlaylistIfOrphan(db, null), false);
});

test('rewriteScheduledPlaylistItem swaps the single item to the new content', () => {
  const db = memdb();
  seedScheduleThrowaway(db, { flagged: 1 });
  db.prepare("INSERT INTO content (id, filename, duration_sec) VALUES ('c2','clip.mp4',32)").run();
  assert.equal(rewriteScheduledPlaylistItem(db, 'pl1', 'c2'), true);
  const items = db.prepare('SELECT content_id, duration_sec FROM playlist_items WHERE playlist_id = ?').all('pl1');
  assert.deepEqual(items.map(i => i.content_id), ['c2']);
  assert.equal(items[0].duration_sec, 32);
});

test('rewriteScheduledPlaylistItem refuses explicit, adopted and unknown targets', () => {
  const db = memdb();
  seedScheduleThrowaway(db, { flagged: 1 });
  db.prepare("INSERT INTO content (id, filename, duration_sec) VALUES ('c2','clip.mp4',32)").run();

  db.prepare('UPDATE playlists SET is_auto_generated = 0 WHERE id = ?').run('pl1');
  assert.equal(rewriteScheduledPlaylistItem(db, 'pl1', 'c2'), false, 'explicit override wins');

  db.prepare('UPDATE playlists SET is_auto_generated = 1 WHERE id = ?').run('pl1');
  db.prepare("INSERT INTO playlist_items (playlist_id, content_id, sort_order) VALUES ('pl1','c1',1)").run();
  assert.equal(rewriteScheduledPlaylistItem(db, 'pl1', 'c2'), false, 'adopted playlist belongs to its human');

  assert.equal(rewriteScheduledPlaylistItem(db, 'pl1', 'ghost'), false, 'unknown content');
  assert.equal(rewriteScheduledPlaylistItem(db, 'nope', 'c2'), false, 'unknown playlist');
});
