'use strict';

/*
 * The room display page's words, in the dashboard's languages (frontend/js/i18n).
 *
 * All of them go into the page, because with the language left on "auto" it is the SCREEN that
 * decides (navigator.languages), not the server: one widget can hang outside rooms in two countries.
 * A key missing from a language falls back to English on the page.
 *
 * The err_* entries replace the server's English refusals (routes/room-panel.js) by their code, so a
 * German panel does not answer a tap in English. Wording follows lib/data-sources/ical-resolver.js
 * ROOM_STRINGS where the two overlap.
 *
 * ⚠️ hi/ja/zh are best-effort and worth a native-speaker check, like ROOM_STRINGS.
 */

const ROOM_PAGE_STRINGS = {
  en: {
    available: 'Available', busy: 'In use', checkin: 'Check in',
    free_until: 'Free until {t}', free_all_day: 'Free for the rest of the day',
    until: 'Until {t}', left: '{n} min left', next: 'Next: {t}', next_free: 'Next free at {t}',
    today: 'Today', no_more: 'No more meetings today',
    private_meeting: 'Private meeting', reserved: 'Reserved', all_day: 'All day', booked_here: 'Booked at the room display',
    book: 'Book {n} min', book_until: 'Book until {t}', end: 'End meeting', check_in: 'Check in',
    release_at: 'Released at {t} if nobody checks in', checked_in: 'Checked in',
    offline: 'Showing the saved schedule — the calendar can’t be reached right now.',
    no_room: 'This room display has no room selected.', working: 'One moment…',
    failed: 'That did not work.', unreachable: 'The server could not be reached.',
    err_busy: 'The room is in use.', err_too_short: 'The next meeting starts too soon to book.',
    err_not_current: 'That meeting is not in progress.',
    err_not_panel: 'Only meetings booked at this display can be ended here.',
    err_booking_off: 'Booking from the display is turned off for this room.',
    err_calendar: 'The calendar refused that. Try again, or book from your calendar.',
    err_limited: 'Too many requests — wait a moment.',
  },
  de: {
    available: 'Frei', busy: 'Belegt', checkin: 'Einchecken',
    free_until: 'Frei bis {t}', free_all_day: 'Für den Rest des Tages frei',
    until: 'Bis {t}', left: 'Noch {n} Min.', next: 'Als Nächstes: {t}', next_free: 'Wieder frei um {t}',
    today: 'Heute', no_more: 'Heute keine weiteren Besprechungen',
    private_meeting: 'Private Besprechung', reserved: 'Reserviert', all_day: 'Ganztägig', booked_here: 'An der Raumanzeige gebucht',
    book: '{n} Min. buchen', book_until: 'Bis {t} buchen', end: 'Besprechung beenden', check_in: 'Einchecken',
    release_at: 'Wird um {t} freigegeben, wenn niemand eincheckt', checked_in: 'Eingecheckt',
    offline: 'Gespeicherter Zeitplan – der Kalender ist gerade nicht erreichbar.',
    no_room: 'Für diese Raumanzeige ist kein Raum ausgewählt.', working: 'Einen Moment …',
    failed: 'Das hat nicht geklappt.', unreachable: 'Der Server ist nicht erreichbar.',
    err_busy: 'Der Raum ist belegt.', err_too_short: 'Die nächste Besprechung beginnt zu bald für eine Buchung.',
    err_not_current: 'Diese Besprechung läuft gerade nicht.',
    err_not_panel: 'Hier können nur Besprechungen beendet werden, die an dieser Anzeige gebucht wurden.',
    err_booking_off: 'Buchen an der Anzeige ist für diesen Raum ausgeschaltet.',
    err_calendar: 'Der Kalender hat das abgelehnt. Versuchen Sie es erneut oder buchen Sie über Ihren Kalender.',
    err_limited: 'Zu viele Anfragen – bitte kurz warten.',
  },
  nl: {
    available: 'Beschikbaar', busy: 'Bezet', checkin: 'Inchecken',
    free_until: 'Vrij tot {t}', free_all_day: 'Vrij voor de rest van de dag',
    until: 'Tot {t}', left: 'Nog {n} min', next: 'Hierna: {t}', next_free: 'Weer vrij om {t}',
    today: 'Vandaag', no_more: 'Vandaag geen vergaderingen meer',
    private_meeting: 'Privévergadering', reserved: 'Gereserveerd', all_day: 'Hele dag', booked_here: 'Geboekt op het ruimtescherm',
    book: '{n} min boeken', book_until: 'Boeken tot {t}', end: 'Vergadering beëindigen', check_in: 'Inchecken',
    release_at: 'Wordt om {t} vrijgegeven als niemand incheckt', checked_in: 'Ingecheckt',
    offline: 'Opgeslagen planning – de agenda is nu niet bereikbaar.',
    no_room: 'Voor dit ruimtescherm is geen ruimte gekozen.', working: 'Een ogenblik…',
    failed: 'Dat is niet gelukt.', unreachable: 'De server is niet bereikbaar.',
    err_busy: 'De ruimte is bezet.', err_too_short: 'De volgende vergadering begint te snel om te boeken.',
    err_not_current: 'Die vergadering is niet bezig.',
    err_not_panel: 'Alleen vergaderingen die op dit scherm zijn geboekt, kunnen hier worden beëindigd.',
    err_booking_off: 'Boeken via het scherm staat uit voor deze ruimte.',
    err_calendar: 'De agenda weigerde dat. Probeer het opnieuw of boek via je agenda.',
    err_limited: 'Te veel verzoeken – wacht even.',
  },
  fr: {
    available: 'Libre', busy: 'Occupée', checkin: 'À confirmer',
    free_until: 'Libre jusqu’à {t}', free_all_day: 'Libre pour le reste de la journée',
    until: 'Jusqu’à {t}', left: 'Encore {n} min', next: 'Ensuite : {t}', next_free: 'Libre à partir de {t}',
    today: 'Aujourd’hui', no_more: 'Plus de réunions aujourd’hui',
    private_meeting: 'Réunion privée', reserved: 'Réservée', all_day: 'Toute la journée', booked_here: 'Réservée sur l’affichage de la salle',
    book: 'Réserver {n} min', book_until: 'Réserver jusqu’à {t}', end: 'Terminer la réunion', check_in: 'Confirmer la présence',
    release_at: 'Libérée à {t} si personne ne confirme sa présence', checked_in: 'Présence confirmée',
    offline: 'Planning enregistré – le calendrier est injoignable pour le moment.',
    no_room: 'Aucune salle n’est sélectionnée pour cet affichage.', working: 'Un instant…',
    failed: 'Cela n’a pas fonctionné.', unreachable: 'Le serveur est injoignable.',
    err_busy: 'La salle est occupée.', err_too_short: 'La prochaine réunion commence trop tôt pour réserver.',
    err_not_current: 'Cette réunion n’est pas en cours.',
    err_not_panel: 'Seules les réunions réservées sur cet affichage peuvent être terminées ici.',
    err_booking_off: 'La réservation depuis l’affichage est désactivée pour cette salle.',
    err_calendar: 'Le calendrier a refusé. Réessayez ou réservez depuis votre calendrier.',
    err_limited: 'Trop de demandes – patientez un instant.',
  },
  es: {
    available: 'Disponible', busy: 'Ocupada', checkin: 'Por confirmar',
    free_until: 'Libre hasta las {t}', free_all_day: 'Libre el resto del día',
    until: 'Hasta las {t}', left: 'Quedan {n} min', next: 'A continuación: {t}', next_free: 'Libre a las {t}',
    today: 'Hoy', no_more: 'No hay más reuniones hoy',
    private_meeting: 'Reunión privada', reserved: 'Reservada', all_day: 'Todo el día', booked_here: 'Reservada en la pantalla de la sala',
    book: 'Reservar {n} min', book_until: 'Reservar hasta las {t}', end: 'Terminar reunión', check_in: 'Confirmar asistencia',
    release_at: 'Se liberará a las {t} si nadie confirma', checked_in: 'Asistencia confirmada',
    offline: 'Mostrando el horario guardado: ahora no se puede acceder al calendario.',
    no_room: 'Esta pantalla de sala no tiene ninguna sala seleccionada.', working: 'Un momento…',
    failed: 'No ha funcionado.', unreachable: 'No se puede contactar con el servidor.',
    err_busy: 'La sala está ocupada.', err_too_short: 'La próxima reunión empieza demasiado pronto para reservar.',
    err_not_current: 'Esa reunión no está en curso.',
    err_not_panel: 'Aquí solo se pueden terminar las reuniones reservadas en esta pantalla.',
    err_booking_off: 'La reserva desde la pantalla está desactivada para esta sala.',
    err_calendar: 'El calendario lo ha rechazado. Inténtalo de nuevo o reserva desde tu calendario.',
    err_limited: 'Demasiadas solicitudes: espera un momento.',
  },
  pt: {
    available: 'Disponível', busy: 'Ocupada', checkin: 'Por confirmar',
    free_until: 'Livre até {t}', free_all_day: 'Livre o resto do dia',
    until: 'Até {t}', left: 'Faltam {n} min', next: 'A seguir: {t}', next_free: 'Livre às {t}',
    today: 'Hoje', no_more: 'Não há mais reuniões hoje',
    private_meeting: 'Reunião privada', reserved: 'Reservada', all_day: 'Dia inteiro', booked_here: 'Reservada no painel da sala',
    book: 'Reservar {n} min', book_until: 'Reservar até {t}', end: 'Terminar reunião', check_in: 'Confirmar presença',
    release_at: 'Liberada às {t} se ninguém confirmar presença', checked_in: 'Presença confirmada',
    offline: 'Horário guardado: o calendário não está acessível neste momento.',
    no_room: 'Este painel de sala não tem nenhuma sala selecionada.', working: 'Um momento…',
    failed: 'Não funcionou.', unreachable: 'Não foi possível contactar o servidor.',
    err_busy: 'A sala está ocupada.', err_too_short: 'A próxima reunião começa demasiado cedo para reservar.',
    err_not_current: 'Essa reunião não está em curso.',
    err_not_panel: 'Aqui só podem ser terminadas reuniões reservadas neste painel.',
    err_booking_off: 'A reserva no painel está desativada para esta sala.',
    err_calendar: 'O calendário recusou. Tente novamente ou reserve no seu calendário.',
    err_limited: 'Demasiados pedidos — aguarde um momento.',
  },
  it: {
    available: 'Libera', busy: 'Occupata', checkin: 'Da confermare',
    free_until: 'Libera fino alle {t}', free_all_day: 'Libera per il resto della giornata',
    until: 'Fino alle {t}', left: 'Ancora {n} min', next: 'Prossima: {t}', next_free: 'Libera dalle {t}',
    today: 'Oggi', no_more: 'Nessun’altra riunione oggi',
    private_meeting: 'Riunione privata', reserved: 'Prenotata', all_day: 'Tutto il giorno', booked_here: 'Prenotata dal display della sala',
    book: 'Prenota {n} min', book_until: 'Prenota fino alle {t}', end: 'Termina riunione', check_in: 'Conferma presenza',
    release_at: 'Verrà liberata alle {t} se nessuno conferma la presenza', checked_in: 'Presenza confermata',
    offline: 'Programma salvato: al momento il calendario non è raggiungibile.',
    no_room: 'Nessuna sala selezionata per questo display.', working: 'Un momento…',
    failed: 'Non ha funzionato.', unreachable: 'Il server non è raggiungibile.',
    err_busy: 'La sala è occupata.', err_too_short: 'La prossima riunione inizia troppo presto per prenotare.',
    err_not_current: 'Quella riunione non è in corso.',
    err_not_panel: 'Qui si possono terminare solo le riunioni prenotate da questo display.',
    err_booking_off: 'La prenotazione dal display è disattivata per questa sala.',
    err_calendar: 'Il calendario ha rifiutato. Riprova o prenota dal tuo calendario.',
    err_limited: 'Troppe richieste: attendi un momento.',
  },
  ja: {
    available: '空き', busy: '使用中', checkin: 'チェックイン待ち',
    free_until: '{t} まで空き', free_all_day: '本日はこの後ずっと空き',
    until: '{t} まで', left: '残り {n} 分', next: '次: {t}', next_free: '{t} から空き',
    today: '今日', no_more: '本日の会議はこれ以上ありません',
    private_meeting: '非公開の会議', reserved: '予約済み', all_day: '終日', booked_here: 'この表示で予約',
    book: '{n} 分予約', book_until: '{t} まで予約', end: '会議を終了', check_in: 'チェックイン',
    release_at: '{t} までにチェックインがなければ解放されます', checked_in: 'チェックイン済み',
    offline: '保存済みの予定を表示しています。現在カレンダーに接続できません。',
    no_room: 'この会議室表示には会議室が選択されていません。', working: 'お待ちください…',
    failed: 'うまくいきませんでした。', unreachable: 'サーバーに接続できません。',
    err_busy: '会議室は使用中です。', err_too_short: '次の会議まで時間が短いため予約できません。',
    err_not_current: 'その会議は進行中ではありません。',
    err_not_panel: 'ここで終了できるのは、この表示で予約した会議だけです。',
    err_booking_off: 'この会議室では表示からの予約がオフになっています。',
    err_calendar: 'カレンダーに拒否されました。もう一度試すか、カレンダーから予約してください。',
    err_limited: 'リクエストが多すぎます。少し待ってください。',
  },
  zh: {
    available: '空闲', busy: '使用中', checkin: '待签到',
    free_until: '空闲至 {t}', free_all_day: '今天剩余时间空闲',
    until: '至 {t}', left: '还剩 {n} 分钟', next: '下一场：{t}', next_free: '{t} 起空闲',
    today: '今天', no_more: '今天没有更多会议',
    private_meeting: '私人会议', reserved: '已预订', all_day: '全天', booked_here: '在会议室显示屏上预订',
    book: '预订 {n} 分钟', book_until: '预订至 {t}', end: '结束会议', check_in: '签到',
    release_at: '如无人签到，将于 {t} 释放', checked_in: '已签到',
    offline: '正在显示已保存的日程——暂时无法连接日历。',
    no_room: '此会议室显示屏未选择会议室。', working: '请稍候…',
    failed: '操作未成功。', unreachable: '无法连接服务器。',
    err_busy: '会议室正在使用中。', err_too_short: '距离下一场会议太近，无法预订。',
    err_not_current: '该会议未在进行中。',
    err_not_panel: '此处只能结束在本显示屏上预订的会议。',
    err_booking_off: '此会议室已关闭显示屏预订。',
    err_calendar: '日历拒绝了此操作。请重试，或在日历中预订。',
    err_limited: '请求过多，请稍候。',
  },
  hi: {
    available: 'उपलब्ध', busy: 'उपयोग में', checkin: 'चेक-इन बाकी',
    free_until: '{t} तक उपलब्ध', free_all_day: 'आज बाकी दिन उपलब्ध',
    until: '{t} तक', left: '{n} मिनट बाकी', next: 'अगली: {t}', next_free: '{t} से उपलब्ध',
    today: 'आज', no_more: 'आज और कोई मीटिंग नहीं',
    private_meeting: 'निजी मीटिंग', reserved: 'आरक्षित', all_day: 'पूरा दिन', booked_here: 'रूम डिस्प्ले पर बुक की गई',
    book: '{n} मिनट बुक करें', book_until: '{t} तक बुक करें', end: 'मीटिंग समाप्त करें', check_in: 'चेक-इन करें',
    release_at: 'कोई चेक-इन नहीं करता तो {t} पर छोड़ दिया जाएगा', checked_in: 'चेक-इन हो गया',
    offline: 'सहेजा गया शेड्यूल दिख रहा है — अभी कैलेंडर से संपर्क नहीं हो पा रहा।',
    no_room: 'इस रूम डिस्प्ले के लिए कोई कमरा नहीं चुना गया है।', working: 'एक क्षण…',
    failed: 'यह काम नहीं हुआ।', unreachable: 'सर्वर से संपर्क नहीं हो पा रहा।',
    err_busy: 'कमरा उपयोग में है।', err_too_short: 'अगली मीटिंग बहुत जल्द शुरू हो रही है, बुकिंग नहीं हो सकती।',
    err_not_current: 'वह मीटिंग अभी नहीं चल रही।',
    err_not_panel: 'यहाँ केवल इसी डिस्प्ले पर बुक की गई मीटिंग समाप्त की जा सकती हैं।',
    err_booking_off: 'इस कमरे के लिए डिस्प्ले से बुकिंग बंद है।',
    err_calendar: 'कैलेंडर ने इसे अस्वीकार कर दिया। फिर से कोशिश करें, या अपने कैलेंडर से बुक करें।',
    err_limited: 'बहुत सारे अनुरोध — थोड़ा रुकें।',
  },
};

const ROOM_PAGE_LANGUAGES = Object.keys(ROOM_PAGE_STRINGS);

module.exports = { ROOM_PAGE_STRINGS, ROOM_PAGE_LANGUAGES };
